apiVersion: v1
kind: ConfigMap
metadata:
  name: beach-runtime
  namespace: beach
data:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8080"
  MANAGEMENT_SERVER_PORT: "8081"
  APP_ENVIRONMENT: production
  SPRING_REDIS_PORT: "6379"
