apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beach
resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
images:
  - name: beach-backend
    newName: ghcr.io/geonusp/beach_complex-k8s-poc-backend
    newTag: latest
